### ISSUE TITLE
Error by search

### ISSUE THREAD

**Issue by MAH1987** [CC007/HeadsInventory#3]
`
[Server thread/INFO]: mah1987 issued server command: /headsinv msearch patrick
[Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'headsinv' in plugin HeadsInventory v1.10.0-rc1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-334]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-334]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[?:git-Paper-334]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[?:git-Paper-334]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1051) ~[patched_1.15.2.jar:git-Paper-334]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.15.2.jar:git-Paper-334]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_252]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_252]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_252]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.15.2.jar:git-Paper-334]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.15.2.jar:git-Paper-334]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-334]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-334]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at com.github.cc007.headsplugin.api.HeadsPluginApi.getHeadSearcher(HeadsPluginApi.java:73) ~[?:?]
	at com.github.cc007.headsinventory.search.HeadsSearch.search(HeadsSearch.java:147) ~[?:?]
	at com.github.cc007.headsinventory.commands.HeadsInventoryCommand.validateArgsAndSearch(HeadsInventoryCommand.java:237) ~[?:?]
	at com.github.cc007.headsinventory.commands.HeadsInventoryCommand.onSearchCommand(HeadsInventoryCommand.java:216) ~[?:?]
	at com.github.cc007.headsinventory.commands.HeadsInventoryCommand.onHeadsInventoryCommand(HeadsInventoryCommand.java:169) ~[?:?]
	at com.github.cc007.headsinventory.commands.HeadsInventoryCommand.onPlayerCommand(HeadsInventoryCommand.java:84) ~[?:?]
	at com.github.cc007.headsinventory.commands.HeadsInventoryCommand.onCommand(HeadsInventoryCommand.java:68) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-334]
	... 17 more`
Its also happend by /headsinv search patrick.
Playerheads works fine

**Comment by MAH1987** [comment]
Tested on papermc 1.15:
`
[11:17:10 INFO]: [HeadsPluginAPI] Enabling HeadsPluginAPI v2.0.0-rc1
[11:17:11 ERROR]: Error occurred while enabling HeadsPluginAPI v2.0.0-rc1 (Is it up to date?)
java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.apache.logging.slf4j.Log4jLoggerFactory loaded from . If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.apache.logging.slf4j.Log4jLoggerFactory
at org.springframework.util.Assert.instanceCheckFailed(Assert.java:696) ~[?:?]
    at org.springframework.util.Assert.isInstanceOf(Assert.java:596) ~[?:?]
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:281) ~[?:?]
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:104) ~[?:?]
    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:239) ~[?:?]
    at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220) ~[?:?]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[?:?]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[?:?]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[?:?]
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[?:?]    at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:70) ~[?:?]
    at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:47) ~[?:?]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[?:?]
    at com.github.cc007.headsplugin.HeadsPlugin.onEnable(HeadsPlugin.java:80) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.jar:git-Paper-20]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.jar:git-Paper-20]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.jar:git-Paper-20]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.jar:git-Paper-20]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.jar:git-Paper-20]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.jar:git-Paper-20]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.jar:git-Paper-20]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.jar:git-Paper-20]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
`

**Comment by MAH1987** [comment]
I didn't see this before:
`[01:32:32] [Server thread/ERROR]: Error occurred while enabling HeadsPluginAPI v2.0.0-rc1 (Is it up to date?)
java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.apache.logging.slf4j.Log4jLoggerFactory loaded from file:/$
        at org.springframework.util.Assert.instanceCheckFailed(Assert.java:696) ~[?:?]
        at org.springframework.util.Assert.isInstanceOf(Assert.java:596) ~[?:?]
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:281) ~[?:?]
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:104) ~[?:?]
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:239) ~[?:?]
        at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[?:?]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[?:?]
        at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:70) ~[?:?]
        at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:47) ~[?:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[?:?]
        at com.github.cc007.headsplugin.HeadsPlugin.onEnable(HeadsPlugin.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-334]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

so i think the main problem is the API not the HeadsPlugin.

**Comment by CC007** [comment]
Fixed by removing Logback so that I'm only using Log4J2.

Btw, I had to disable the SysOut appender in spigot though (seems to normally be disabled by default), because it caused logs to be printed twice in console. Disabling the SysOut appender fixed this. 

This has no effect on PaperMC at all, because it doesn't define a SysOut appender and therefore didn't have the same issue.
